import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { TheHeader } from "@/components/TheHeader";
import "./globals.css";
import { TheFooter } from "@/components/TheFooter";
import { ToDoListContextProvider } from "@/context/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TO DO LIST",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TheHeader />
        <main>
          <ToDoListContextProvider>{children}</ToDoListContextProvider>
        </main>
        <TheFooter />
      </body>
    </html>
  );
}
